steps:
  verify:
    image: ghcr.io/cirruslabs/flutter:stable
    commands:
      - ./gradlew :core:check --no-configuration-cache
      - cd flutter
      - flutter pub get
      - flutter analyze

when:
  - event: [push, pull_request, manual]
